In [31]:
import numpy as np
from numpy.linalg import inv, det

#1. Membuat Tensor

In [32]:
a = [[23,50],
     [7,12]]
b = [[57,67],
     [99,43]]
c = [[75,21],
     [57,12]]
d = [[87,26],
     [18,84]]

A = np.array(a)
B = np.array(b)
C = np.array(c)
D = np.array(d)


In [33]:
print(A)
print(B)
print(C)
print(D)


[[23 50]
 [ 7 12]]
[[57 67]
 [99 43]]
[[75 21]
 [57 12]]
[[87 26]
 [18 84]]


In [34]:
Tensor = np.array(
    [[[23,50],[7,12]],[[57,67],[99,43]],
     [[75,21],[57,12]],[[87,26],[18,84]]]
)

print(Tensor)

[[[23 50]
  [ 7 12]]

 [[57 67]
  [99 43]]

 [[75 21]
  [57 12]]

 [[87 26]
  [18 84]]]


In [35]:
Tensor.shape

(4, 2, 2)

#2. Melakukan perkalian

In [36]:
a = [[23,50,19],
     [7,12,109],
     [57,67,98]]
b = [[17],
     [22],
     [19]]
c = np.dot(a,b)

In [37]:
print(c)

[[1852]
 [2454]
 [4305]]


#3. Mencari Transpose, determinan, dan ivers matrix

In [38]:
m_a = [[23,50,19],
     [7,12,109],
     [57,67,98]]

###Transpose Matrix

In [39]:
def Transpose(m_a):
  for i in range(len(m_a)):
    for j in range(len(m_a[0])):
      result[j][i] = m_a[i][j]

m_a = [[23,50,19],
     [7,12,109],
     [57,67,98]]

result = [[0,0,0],
          [0,0,0],
          [0,0,0]]

Transpose(m_a)

In [40]:
for hasil_transpose in result:
  print(hasil_transpose)

[23, 7, 57]
[50, 12, 67]
[19, 109, 98]


###Determinan Matrix

In [41]:
det(m_a)

131344.0000000002

In [42]:
round(det(m_a),2)

131344.0

###Invers Matrix

In [43]:
inv(m_a)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])

In [44]:
#cara lain invers
np.linalg.inv(m_a)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])